### ISSUE TITLE
Referencing external modules?

### ISSUE THREAD

**Issue by alukach** [aws/jsii-docgen#129]
I'm trying utilize `jsii-docgen` to generate documentation for some custom CDK constructs I'm publishing. These constructs extend the `Construct` class of `aws-cdk.core`.  If I attempt to generate documentation for only a single package's `.jsii` file (e.g. 
`npx jsii-docgen --output docs .jsii`), an error is thrown `Error: Assembly "@aws-cdk/core" not found` (this is because `core.Construct` is the base of my construct).

I can generate documentation for all of my packages (e.g. `npx jsii-docgen --output docs **/.jsii`), however this generates (and links to) documentation for all of the CDK packages referenced within my constructs.  I have no intention of publishing the CDK documentation, I'd prefer to either not link to any non-internal module or to perhaps link to the external CDK docs.

Are there any facilities available to support this? Or is my only solution to generate documentation for all referenced CDK classes and then delete it (and its references) in a post-processing step?

**Comment by eladb** [comment]
If you just run `jsii-docgen` (with no arguments) from your module root I believe it will only produce an API.md file that includes the classes in that module.

**Comment by alukach** [comment]
Thanks @eladb. I was aware of this option but found it less ideal as it doesn't create a helpful `README.md` in the same fashion as `jsii-docgen --output docs .jsii`.  I'm going to dig in to using the codebase as a library rather than a CLI and will report back in this ticket.

A side question: is there any codebase where I can see how the AWS CDK docs are generated? I'm guessing something is taking the output of `jsii-docgen` and then turning that into HTML (possibly via some out-of-the-box static site generator?).  I'm curious as to how that works and how the docs for the other languages are generated.

**Comment by eladb** [comment]
Copying @rix0rrr as he is working on a new version for docgen. Generally CDK docs are generated using a different tool (jsii-docgen is a fork of it).

**Comment by alukach** [comment]
I had gotten as far as digging into [`aws-devlib`](https://github.com/awslabs/aws-delivlib#github-pages) however being as I'm not using CodeDeploy, I put it down in favor of working towards this issue's topic.

Regarding generating documentation for only my packages, I think I may have something usable with the following:

```js
import yargs from "yargs";
import { renderPages } from "jsii-docgen";
import jsiiReflect from "jsii-reflect";
import path from "path";
import fs from "fs-extra";

const cdkVersion = "latest";

const isLocalFqn = (type) => type.fqn.startsWith("@cdk-seed");
const getCleanedFqn = (type) => type.fqn.replace("/", "_");
const getRelLink = (type) => `./${getCleanedFqn(type)}.md`;
const getCdkLink = (type) =>
  `https://docs.aws.amazon.com/cdk/api/${cdkVersion}/docs/` +
  `${getCleanedFqn(type)}.html`;

export async function renderFiles(jsiiFiles, outdir) {
  const ctx = {
    links: {
      renderLink: (type) =>
        isLocalFqn(type) ? getRelLink(type) : getCdkLink(type),
    },
  };

  const ts = new jsiiReflect.TypeSystem();
  for (const filePath of jsiiFiles) {
    await ts.load(filePath);
  }

  const pages = await renderPages(ts, ctx);
  for (const page of pages) {
    if (!isLocalFqn(page.type)) {
      // console.log(`skipping ${page.type.fqn}`);
      continue;
    }
    console.log(page.type.fqn);
    const filePath = path.join(outdir, getRelLink(page.type));
    await fs.mkdirp(path.dirname(filePath));
    await fs.writeFile(filePath, page.markdown, { encoding: "utf-8" });
  }
}

export async function main() {
  const args = yargs
    .usage("Usage: $0 [JSII-FILE,...]")
    .option("output", {
      type: "string",
      alias: "o",
      required: false,
      desc: 'Output directory or file (default directory is "dist")',
    })
    .example(
      "$0 node_modules/**/.jsii",
      "Generate documentation for all jsii modules in your project"
    ).argv;

  const output = args.output ?? "dist";
  await renderFiles(args._, output);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
```

Of course, the above assumes that only CDK libraries will be used as base libraries within my constructs.  I'm going to close this for now, but please feel free to point out anything I may be missing (or if @rix0rrr has any advice regarding where to find info on either how CDK docs are build or building documentation for other languages).
